import React from 'react';
import { Link } from 'react-router-dom';

function Porn(){
    return(
<div className="mt-5 m-auto p-5 w-4/5 text-dark bg-bg-gray rounded-lg dark:text-bg-gray dark:bg-navy">
    <div className="md:w-4/5 sm:w-7/8 mr-auto ml-auto">
<h1 className="text-lg text-darkdark:text-bg-gray font-bold text-center">Preface</h1>

<div className="text-base text-dark dark:text-bg-gray">
You probably clicked on this link out of a devious curiosity, so I am sorry to disappoint. The nature of this article is entirely more serious. Having been raised in a fairly religious household, I was told that pornography was evil and that, contrary to my basic human desires, must refrain from partaking in it. This led to substantial internal dissonance as I was caught between my religious upbringing and the powerful desires that pornography so easily instigates. In this struggle, I decided to begin my own research and figure out if there is more to the story than unlimited pleasure and strict abstinence. I have made an incredible number of discoveries that sparked me to begin compiling all the research I could find and create a medium with which to share this knowledge with others. The fruition of this website is something I am quite proud of since this whole project has been over five years in the making. I was going to analyze relationships through the lens of internet pornography as my senior thesis for my undergraduate degree, although I was advised that I did not have enough time to finish it. Despite this setback, I chose to continue working on it and have concluded that pornography, through its physical, social, and mental harms, really is the toxic poison for true, meaningful relationships, to say nothing of its spiritual harms. Make no mistake, however, that this analysis includes religious or other biases as I have taken great care to only focus on published research.</div>

<h1 className="text-lg text-center text-darkdark:text-bg-gray font-bold">Introduction</h1>
<div className="text-base text-dark dark:text-bg-gray">
In the year 2019, the world uploaded 169 years' worth of pornographic videos onto one website. For perspective, former U.S. President Millard Fillmore would still be watching the content that was uploaded to one website in one year if he had started watching it during his presidency in 1852 [1]. The stunning quantity of pornography created and consumed warrants an analysis of how this media attracts such popularity and, since it popularizes the most intimate parts of relationships, if it adversely effects other facets of life, specifically real-life relationships. A thorough analysis of the available literature reveals that pornography addicts consumers by offering an easy, idealized alternative to personal intimacy which undermines real relationships and causes separation and divorce among couples.</div>

<h1 className="text-lg text-center font-bold">Historical Pornography Usage</h1>
<div className="text-base text-dark dark:text-bg-gray">
The world watches a significant amount of pornography, or Sexually Explicit Material (SEM) as it is referred to in the literature, every year; so much so that the largest SEM websites in the world must break down their internet traffic statistics by minutes in order for normal people to comprehend and appreciate them. Tube sites like, where users upload their own content, garner an astonishing number of visits. Pornhub, the most popular tube site in the world, rakes in over 90 million visits per day. At this rate, it would take just over two months for every person on Earth to visit the site [2]. Similarly, visitors to the site consume an astronomical amount of content. Using Pornhub's 2019 data, the website reports that visitors to the website watched 664,920 hours of SEM every hour. That means over 11,000 hours of SEM videos are watched every 60 seconds. Furthermore, visitors watched over 13 million videos every hour, meaning 216,985 videos every minute [1]. The United States, according to Pornhub's 2019 data, far and away consumes the most content on the site [3]. Internet research organization WebRoot calculates that 40 million Americans regularly visit SEM sites [4]. The incredible amount of time that people spend watching pornography and growing concerns has prompted research into the multi-billion-dollar industry to study the effects on people and relationships which will be discussed.</div>

<h1 className="text-lg text-center font-bold">Literature Review</h1>
<h2 className="font-bold text-center">Introduction</h2>
<div className="text-base text-dark dark:text-bg-gray">
One of the reasons that Sexually Explicit Material (SEM) has grown so popular stems from its powerful capitalization of human neuroplasticity and neurochemistry to form addictions. Traditional addiction theory must be understood if SEM's seemingly unbreaking grip on the mind of humanity is to be understood. The most powerful stimuli satisfy basic human needs such as eating, engaging in social environments, sex, and other fundamental needs in Maslow's Hierarchy of needs. These activities trigger the release of the most powerful chemicals in the brain like dopamine which is triggered when people engage in activities proven useful in evolution [5].</div>

<h2 className="font-bold text-center">Addiction Model</h2>
<div className="text-base text-dark dark:text-bg-gray">
Sexually Explicit Material causes the release of powerful neurochemicals that human evolution has built up over centuries. Maslow categorized the needs of people into a pyramid with the most basic needs at the bottom such as food, water, shelter, and reproduction. SEM taps into the most basic need of reproduction by simulating and stimulating those neural pathways [6]. When a viewer first encounters SEM, they experience what researchers call the “Binge/Intoxication Stage” where addiction first begins because the stimulus is associated with the dopamine rush [7]. After experiencing SEM, the viewer enters the “Withdrawal/Negative Affect Stage”. After the initial rush, other smaller stimuli that might otherwise have elicited a dopamine response, albeit a smaller one than the addictive stimulus, do not. Dopamine receptors in the brain have become “saturated” from the rush of dopamine due to a chemical called Dynorphin. The release of Dynorphin decreases receptivity to neurochemicals like Dopamine but simultaneously increases sensitivity to that stimulus. This effect can lead to lasting tolerance and to feelings of anxiety, depression, dysphoria, and irritability [8], [7], [9]. The third state of addition, “Preoccupation/Anticipation Stage”, occurs when the dopamine response is temporarily compromised. In this stage of the cycle, a brain's neuroplasticity has created or reinforced pathways in other areas of the brain, and it has become dependent on the stimulus to maintain baseline levels of dopamine. This effect manifests itself as a yearning or craving feeling to achieve the high that it previously experienced [10], [8]. Love, et al. find SEM addiction consistent with this model that was originally conceived with only drug addiction in mind [8]. Scientific theories about the human brain have evolved over time just like any scientific structure, and scientists have broken human desires into two different categories: liking and wanting. Liking means a fundamental and biological attraction towards specific activities like hobbies or pastimes. Conversely, people learn how to want based on the neurochemical reactions of the human brain to stimuli, or broadly pursuing things that result in dopamine release. Examples of wanting include drug dependencies and addiction [11].</div>

<h2 className="font-bold text-center">Addictive Properties of SEM</h2>
<div className="text-base text-dark dark:text-bg-gray">
In one FMRI study of 57 heterosexual males ages 18-48, 31 seeking treatment for Problematic Pornography Usage (PPU) and 26 control subjects were given a series of tests.  Exposure to SEM was the reward for answering questions correctly, meaning they had stronger motivations for getting the question correct. Men seeking treatment for PPU exhibited more activity in the ventral striatum (the pleasure center of the brain) during the anticipatory phase of the test than the control group. Subjects reporting PPU showed higher sensitivity to Sexually Explicit Material (SEM) than control group, showing that PPU alters the motivational process [12]. Gola, et al. also found that strength of fMRI results significantly correlated to frequency of SEM use and masturbation [12].</div>

<h2 className="font-bold text-center">Violent Tendancies</h2>
<div className="text-base text-dark dark:text-bg-gray">
An analysis of 4009 scenes from the top categories of two tube sites reveals disturbing statistics regarding the treatment of porn actresses. Almost half (45%) of pornographic videos depict physical aggression towards women who make up 97% of the recipients of the violence and who almost exclusively react in neutral or positive manners [15]. The agents who coordinate porn actors and actresses and porn film companies intentionally withhold from the actors or actresses what a porn scene will include until after extensive preparation for the scene has been completed, such as hair, makeup, and videography, to reduce the likelihood of an actor or actress turning down a role [16]. Thus, actors and actresses undergo manipulation to carry out violent sex acts that normal spouses or partners will not. Married men or male partners who view SEM grow accustomed to encountering this violent behavior in intimacy due to SEM's escalating properties. Additional studies show that the violent behaviors are not enjoyed by the spouses or partners of porn viewers who find them “objectionable or demeaning” to the point of filing for divorce [17].</div>

<h1 className="text-lg font-bold text-center">Porn's Effect on Relationship</h1>
<div className="text-base text-dark dark:text-bg-gray">
A 2019 analysis of 30 nationally representative surveys found SEM use to be associated with worse relationship quality for both men and women in both married and unmarried relationships. This study carries special weight because it controlled for other factors that scholars had previously found problematic when drawing conclusions from datasets. While this study shies away from claiming a causal link between SEM exposure and lower quality relationships, it offers a basis for other studies [17].</div>

<div className="text-base text-dark dark:text-bg-gray">
Viewing SEM more than once per month is correlated with decreased relationship satisfaction and dissatisfaction increases with frequency of SEM use. [10].
</div>

<div className="text-base text-dark dark:text-bg-gray">
Ward found by analyzing 135 studies, the negative effects of regular SEM usage in participants daily lives and even in regular but controlled laboratory settings associates with a variety of modern societal problems and phenomena. First, SEM was associated with lowered body positivity [21]. In recent years, advertising and social media{'’'}s role in setting standards of beauty has contributed to body positivity and eating disorder issues. It is possible that pornography is partially responsible for this trend, as no one questioned standards of beauty prior to the recent decade and the explosion of the internet, internet-connected phones, and social media. Now, more than ever, people are subconscious about their bodies and dissatisfied by how they look, likely due to the comparisons that they automatically make with others in the virtual medium, of which porn is a prominent category [22]. Second, Ward{'’'}s research also indicated a strong association between SEM and combative beliefs of the sexes, greater tolerance of sexual violence toward women, and most crucially, the objectification of romantic partners [21]. The last and most important issue of objectification of romantic partners results in less relationship and sexual satisfaction in couples [23]. It is possible that this phenomena is fueled in part by the greater societal effect of increased SEM consumption and lower average ages of first exposure to SEM, or when viewers are more impressionable. 
</div>

<h2 className="font-bold text-center">Divorce</h2>
<div className="text-base text-dark dark:text-bg-gray">
According to Doran and Price, watching SEM made married adults more than twice as likely to be divorced in six years, cheat on their spouse, and report less happiness in their marriage than control groups who did not view SEM [18].</div>

<h2 className="font-bold text-center">Conclusion</h2>
<div className="text-base text-dark dark:text-bg-gray">
Having explored the literature regarding this taboo topic, it is clear that viewing SEM has negative effects on the viewer, such as developing negative or unrealistic views on intimacy, body image dissatisfaction, anxiety, and depression, all while entrapping the viewer deeper into the cycle of addiction. Related issues such as the neurochemical and psychological effects were also discussed to explain and frame the discussion. Finally, the effect of the aforementioned harms were associated with the effects SEM has on relationships, which from the literature are only negative outcomes. The trickledown effect of the damage SEM does to relationships, namely divorce and breakups, can negatively effect children of those relationships, however that is outside the scope of this research. In conclusion, SEM has disastrous effects on intimacy and relationships, and those in relationships would be wise to evaluate their SEM use, as SEM and happy, satisfying relationships are mutually exclusive to one-another.
</div>

<h2 className="font-bold text-center">Postscript</h2>
<div className="text-base text-dark dark:text-bg-gray">
The goal of this paper was to present in scientific format and with absolute academic rigor, the literature related to SEM's effect on relationships. I want people to be aware of the subtle harms that mainstream SEM causes to individuals, and more crucially to couples. I have seen firsthand the effect that cutting out porn/SEM has on individuals, and I want people who feel stuck and numbed to experience the excitement and beauty of the world around them instead of being a desensitized slave to their passions. 
</div>

<div className="text-base text-dark dark:text-bg-gray">
If you found this essay pursuasive and are interested in learning more, you can read my subsequent article that has other media I have encountered that is easier to digest than these highly scientific articles. There are YouTube videos, articles, and analyses that have also informed my opinions on this topic. It also contains my personal experience with cutting porn out of my life and tips I have since I have found it to be a challenging endeavor. <Link className='text-lowTeal hover:text-midTeal text-md dark:hover:text-midTeal' to='/essays/Recover'>Porn Essay 2</Link>.
</div>

    <h1 className="font-bold text-lg text-center">References</h1>
<div className="text-base text-dark dark:text-bg-gray">[1] 	Pornhub, "The 2019 Year in Review," 11 December 2019. [Online]. Available: https://www.pornhub.com/insights/2019-year-in-review#2019.</div>
<div className="text-base text-dark dark:text-bg-gray">[2] 	B. Montgomery, "Porn Stars Are Getting Personal To Combat Piracy," 24 July 2018. [Online]. Available: https://www.buzzfeednews.com/article/blakemontgomery/porn-pornhub-mindgeek-girlfriend-experience?bfsource=relatedmanual.</div>
<div className="text-base text-dark dark:text-bg-gray">[3] 	J. M. Ruxton, "The most-watched porn of 2017 and the horniest countries," 10 January 2018. [Online]. Available: https://www.buzz.ie/life-style/watched-porn-2017-horniest-countries-268463.</div>
<div className="text-base text-dark dark:text-bg-gray">[4] 	WebRoot, "Internet Pornography by the Numbers; A Significant Threat to Society," [Online]. Available: https://www.webroot.com/us/en/resources/tips-articles/internet-pornography-by-the-numbers#:~:text=40%20million%20American%20people%20regularly,of%20porn%20viewers%20are%20women..</div>
<div className="text-base text-dark dark:text-bg-gray">[5] 	E. J. Nestler, "Is there a common molecular pathway for addiction?," Nature Neuroscience, pp. 1445-1449, 5 October 2005. </div>
<div className="text-base text-dark dark:text-bg-gray">
<div className="text-base text-dark dark:text-bg-gray">[6] 	V. Zeigler-Hill, Maslow's Hierarchy of Needs, Cham: Springer International Publishing, 2020, p. 2771.</div>
<div className="text-base text-dark dark:text-bg-gray">[7] 	N. D. Volkow, G.-J. Wang, J. S. Fowler, D. Tomasi and F. Telang, "Addiction: Beyond dopamine reward circuitry," Proceedings of the National Academy of Sciences of the United States of America, p. 15037–15042, 2011. </div>
<div className="text-base text-dark dark:text-bg-gray">[8] 	T. Love, C. Laier, M. Brand, L. Hatch and R. Hajela, "Neuroscience of Internet Pornography Addiction: A Review and Update," Behavioral Sciences, pp. 388-433, 2015. </div>
<div className="text-base text-dark dark:text-bg-gray">[9] 	G. F. Koob and N. D. Vokow, "Neurocircuitry of addiction," Neuropsychopharmacology : official publication of the American College of Neuropsychopharmacology, p. 217–238, 2010. </div>
<div className="text-base text-dark dark:text-bg-gray">[10] 	P. J. Wright, A. J. Bridges, C. Sun, M. B. Ezzell and J. A. Johnson, "Personal Pornography Viewing and Sexual Satisfaction: A Quadratic Analysis," Journal of Sex & Marital Therapy, pp. 308-315, 2017. </div>
<div className="text-base text-dark dark:text-bg-gray">[11] 	K. C. Berridge and T. E. Robinson, "Liking, wanting, and the incentive-sensitization theory of addiction," American Psychologist, pp. 670-679, 2016. </div>
<div className="text-base text-dark dark:text-bg-gray">[12] 	M. Gola, M. Wordecha, G. Sescousse, M. Lew-Starowicz, B. Kossowski, M. Wypych, S. Makeig, M. N. Potenza and A. Marchewka, "Can Pornography be Addictive? An fMRI Study of Men Seeking Treatment for Problematic Pornography Use," Neuropsychopharmacology, p. 42, 2017. </div>
<div className="text-base text-dark dark:text-bg-gray">[13] 	L. J. M. Vanderschuren and R. C. Pierce, "Sensitization Processes in Drug Addiction," Curr Top Behav Neurosci, pp. 179-195, 2010. </div>
<div className="text-base text-dark dark:text-bg-gray">[14] 	A. Wery and J. Billieux, "Online sexual activities: An exploratory study of problematic and non-problematic usage patterns in a sample of men," 14 December 2015. [Online]. Available: https://www.sciencedirect.com/science/article/abs/pii/S0747563215302612?via=ihub.</div>
<div className="text-base text-dark dark:text-bg-gray">[15] 	R. Jensen, Getting off: Pornography and the End of Masculinity, South End Press, 2007. </div>
<div className="text-base text-dark dark:text-bg-gray">[16] 	J. D. Foubert, M. W. Brosi and S. R. Bannon, "Pornography Viewing among Fraternity Men: Effects on Bystander Intervention, Rape Myth Acceptance and Behavioral Intent to Commit Sexual Assault," Sexual Addiction & Compulsivity, vol. 18, pp. 212-231, 2011. </div>
<div className="text-base text-dark dark:text-bg-gray">[17] 	ASHCROFT v. FREE SPEECH COALITION, 2002.</div>
<div className="text-base text-dark dark:text-bg-gray">[18] 	M. V. P. B. Z. Y. Fritz N, "A Descriptive Analysis of the Types, Targets, and Relative Frequency of Aggression in Mainstream Pornography," Arch Sex Behav, pp. 3041-3053, 2020. </div>
<div className="text-base text-dark dark:text-bg-gray">[19] 	B. Nolot, Director, Beyond Fantasy - Ep 3: "Hardcore" | PORN INDUSTRY DOCUMENTARY. [Film]. 2023. </div>
<div className="text-base text-dark dark:text-bg-gray">[20] 	B. M. W. &. B. R. S. Foubert, "Pornography Viewing among Fraternity Men: Effects on Bystander Intervention, Rape Myth Acceptance and Behavioral Intent to Commit Sexual Assault," Sexual Addiction & Compulsivity, p. 212–231, 2011. </div>
<div className="text-base text-dark dark:text-bg-gray">[21] 	L. M. Ward, "Media and Sexualization: State of Empirical Research," Sex and Research, vol. 53, no. 4-5, pp. 560-577, 2016. </div>
<div className="text-base text-dark dark:text-bg-gray">[22] 	G. Holland and M. Tiggemann, "A systematic review of the impact of the use of social networking sites on body image and disordered eating outcomes," Body Image, vol. 17, pp. 100-110, 18 March 2016. </div>
<div className="text-base text-dark dark:text-bg-gray">[23] 	E. L. Zurbriggen, "Objectification, Self-Objectification, and Societal Change," Social and Political Psychology, vol. 1, no. 1, pp. 188-215, 2013. </div>
<div className="text-base text-dark dark:text-bg-gray">[24] 	S. L. Perry, "Pornography and Relationship Quality: Establishing the Dominant Pattern by Examining Pornography Use and 31 Measures of Relationship Quality in 30 National Surveys," Archives of Sexual Behavior, 2 January 2020. </div>
<div className="text-base text-dark dark:text-bg-gray">[25] 	K. Doran and J. Price, "Pornography and Marriage," Journal of Family and Economic Issues, no. 35, pp. 489-498, 28 February 2014. </div>
<div className="text-base text-dark dark:text-bg-gray">[26] 	M. &. L. M. A. Eberstadt, The Social Costs of Pornograph: A Statement of Findings and Recommendations, Princeton, MJ: The Witherspoon Institute, 2010. </div>
<div className="text-base text-dark dark:text-bg-gray">[27] 	R. W. E. S. C. S. R. L. Ana J Bridges, "Aggression and sexual behavior in best-selling pornography videos: a content analysis update," PubMed, p. 1065–1085, 16 October 2010. </div>
<div className="text-base text-dark dark:text-bg-gray">[28] 	J. J. Lehmiller, "How the Pandemic Is Changing Pornography," 23 March 2020. [Online]. Available: https://www.psychologytoday.com/us/blog/the-myths-sex/202003/how-the-pandemic-is-changing-pornography.</div>
<div className="text-base text-dark dark:text-bg-gray">[29] 	D. M. Szymanski and R. Mikorski, "Masculine norms, peer group, pornography, Facebook, and men{'’'}s sexual objectification of women.," American Psychological Association, p. 257–267, 2017. </div>
<div className="text-base text-dark dark:text-bg-gray">[30] 	The Economist, "Pornography is booming during the covid-19 lockdowns," 10 May 2020. [Online]. Available: https://www.economist.com/international/2020/05/10/pornography-is-booming-during-the-covid-19-lockdowns.</div>
<div className="text-base text-dark dark:text-bg-gray">[31] 	"2022 Global Digital Trust Insights," October 2021. [Online]. Available: https://www.pwc.com/us/en/assets/cyber-global-digital-trust-insights.pdf.</div>
</div>
    </div>
</div>
    );
}
export default Porn;
