import React from "react";
import { Link } from "react-router-dom";

function StopPorn(){
    return(
<div class="mt-5 m-auto p-5 w-4/5 text-dark bg-bg-gray rounded-lg dark:text-bg-gray dark:bg-navy">
    <div class="md:w-4/5 sm:w-7/8 mr-auto ml-auto">
        <h1 class="text-lg text-darkdark:text-bg-gray font-bold text-center">Introduction</h1>

        <p class="text-base text-dark dark:text-bg-gray">
            If you read my other article, you know of the threat porn poses to healthy relationships and might be interested in learning more about it. There are several websites and a documentary series that were particularly good at aproximating the problems of the industry. They give sobering insight into the porn industry's effects on those both in front of the camera and those behind it. Thereare also several tools, both paid and free that have helped me stop watching porn. I also detail some ways that my life has improved after having quit.
        </p>

        <h1 class="text-lg text-darkdark:text-bg-gray font-bold text-center">Information</h1>
        <p class="text-base text-dark dark:text-bg-gray">
            A psychologist named Gary Wilson wrote a book on the neurological effects porn has on the human brain called 'Your Brain on Porn' where he details ad nauseum the relevant literature. If you are interested in just the studies, his website <Link class='text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal' to='https://www.yourbrainonporn.com/'>Your Brain on Porn</Link> has plenty of reading. Full disclosure: I have not read his book, but the research he has compiled on his site is quite compelling, and many of the studies I discuss in my paper originate from there. If you want an simpler website to interface with specific studies with a short synopsis about each and the ability to search for scientific literature by subtopic related to porn, this website <Link class='text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal' to='https://truthaboutporn.org/'>Truth About Porn</Link> does a fantastic job of making highly technical studies available to the average reader. It is run by a non-profit called <Link class='text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal' to='https://fightthenewdrug.org/'>Fight The New Drug</Link> which is dedicated to sharing research about the harms of pornography on the brain, heart, and mind.
        </p>
        <p class="text-base text-dark dark:text-bg-gray">
            Magic Lantern Productions, a channel on YouTube, made a three-part documentary on the underreported harms of the pornography industry on porn actors. The first video, called <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.youtube.com/watch?v=NVr0jfVt7F0'>Beyond Fantasy: Barely Legal</Link>, focuses on the recent trend in porn that depicts women as underrage. This phenomenon was observed by Nicholas Kristof in his bombshell New York Times article that investigated the prevalence of illegal porn on popular sites. Pornhub used to track usage statistics from their site and compile them into a report at the end of every year, until controversial search terms like "Teen", "Young", and other dubiously legal terms appeared at the top of the report. <Link class="text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.nytimes.com/2020/12/04/opinion/sunday/pornhub-rape-trafficking.html'>That same New York Times investigation</Link> by Nicholas Kristof also showed Pornhub failed to properly vet videos uploaded to the site for child pornography, and such content was easily available to anyone. In the wake of this investigation, major credit card companies dropped service for the site, and it was forced to remove millions of unverified videos from the platform. It should be noted that this documentary series does depict some disturbing content to prove the claims of the actors, and while it is blurred out, it is still not safe for work. I think it is important to humanize the actors that porn denigrates and depicts in a one-dimensional manner to understand the harms that participating in the industry supports.
        </p>

        <p class="text-base text-dark dark:text-bg-gray">
            The second video shares the experiences of actors with sexually transmitted diseases in the industry, how porn companies take safety shortcuts to ensure profits such as lax and ineffective STD testing which endangers actors and actresses.<Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.youtube.com/watch?v=XqcHIMOI204'>Beyond Fantasy: Unsafe Sex</Link>. This episode does a terribly good job juxtaposing the experiences of actors and actresses with the corporate speak peddled by some high-ups in the MindGeek leadership. If someone only heard MindGeek's claims about their STD testing, then they certainly believe them. Having heard the side of the actors and actresses who must actually undergo the testing, then the starkness of the insufficiencies come into focus.
        </p>

        <p class="text-base text-dark dark:text-bg-gray">
            The third video, called <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.youtube.com/watch?v=NVr0jfVt7F0'>Beyond Fantasy: Hardcore</Link>, exposes the porn industry's manipulation of women to get them to film dangerous, violent, and often illegal scenes against their will, including rape. One tactic porn producers use only give the script to the actress after she is onsite and finished with makeup and other preparation to decrease the chance that she will turn down the scene which usually includes things that the actress does not want to do.
        </p>

        <h1 class="text-lg text-darkdark:text-bg-gray font-bold text-center">Resources for Cutting Out Porn</h1>
        <p class="text-base text-dark dark:text-bg-gray">
            There are several different theories on how to quit this habit. You might want to understand your relapses in detail, such as the days that you are most likely to relapse, the places, emotions, and events that contribute to relapses, etc. The Fortify app on app stores is a valuable resource for tracking victories and setbacks in this journey. You report these metrics through daily check-ins. They also have video series to understand the theory behind things you can do to grow out of addictive habits like porn. I have used this app for many years (which is why I know the exact date I started tracking my progress). Recently, however, I have stopped tracking with the app because it requires porn to always be on my mind since the user must track whether each day was a victory or a setback. I view not watching porn as a lifestyle instead of a destination to achieve. I have finished the video series and have begun to understand the physical factors that contribute to relapses. Every major sports team uses in-depth metrics to track athletic performance, so you will need to figure out for yourself how you want to approach this. One additional perspective that must be understood is the inner factors that might contribute to a habit of porn. <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.youtube.com/watch?v=y9Z-fORv1eM&t=198s'>What Sexual Desires Reveal About You</Link> is an interview with a Christian psychologist who has researched the origins of porn in the human person and discusses how certain types of porn might be indications of wounds or traumas that have not been healed yet. Him and his team have identified thousands of personality "profiles" for different types of porn. The research is well worth the read <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://jay-stringer.com/content/'>here</Link> or wherever you find cheap/free books. Full disclosure, I have not read his book, but he has discussed his research in several podcasts.
        </p>
        <p class="text-base text-dark dark:text-bg-gray">
            I found the <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://exodus90.com/'>Exodus 90</Link> program to be crucial in developing a stronger faith, building fraternity, growing self-control, and appreciating good things in moderation. It is a 90-day program beginning in January and ending on Easter Sunday where participants abstain from things that modern men typically rely on for happiness such as social media, games, sweets, snacking, alcohol, warm showers, and other comforts. You will be paired up with one other man as an accountability partner that you will check-in with each day to talk about the daily Bible readings and reflections. Exodus 90 fraternities usually have three or four pairs of men who meet once a week and partake in regular group activities. The Bible readings follow the journey of the Isrealites out of slavery to the Egyptians, a fitting parallel to the modern man spurning reliance on or addiction to material goods and reodering the self towards God and an appreciation of His gifts. It is built for Catholics and certain parts cater to the Catholic faith, but anyone, and certainly any Christian, would certainly get value out of it and would be able to participate in almost every part of it. There is a similar program for women called <Link class=" text-lowTeal hover:text-midTeal text-lg dark:hover:text-midTeal" to='https://www.mag90.com/'>Magnify90</Link>.
        </p>
        <p class="text-base text-dark dark:text-bg-gray">
            Covenant Eyes is also a valuable application with Android, Apple, and Windows versions that protects a user from porn and provides an accountability framework. The app works by optionally routing all traffic on a device through a custom VPN that filters pornographic websites and enforces Safe Search settings on Google. The application also has an optional screen monitor that uses random screenshots and machine learning algorithms to flag pornographic content on a screen. Trusted relatives or friends can receive notifications if such material is detected so that they can help break the cycle and intervene. Google, Apple, and Windows all have built-in safe search features to limit access to this material as well. While you cannot do this with Covenant Eyes, you can change your DNS servers on your home network or devices to OpenDNS or Quad9 which will not respond to inappropriate DNS requests. You should do that anyway since Quad9 DNS servers will block requests to known malicious websites.
        </p>
        <p class="text-base text-dark dark:text-bg-gray">
            One thing I noticed after having stopped watching porn is that I appreciate little things in life that most people might not realize. Sunsets, nature, and other random sights have a whole new beauty. I also find joy in the most common occurrances. It is a miracle what a dopamine-saturated brain misses every day in life. A good friend and I have both quit watching porn and have noticed very similar experiences. We are able to live in the moment and appreciate so much more when we are not governed by porn. We also have more time for hobbies and activities that facilitate genuine happiness as opposed to feeding a habit that has no value to others.
        </p>
    </div>
</div>
    );
}
export default StopPorn;